### ISSUE TITLE
Helm repository ?

### ISSUE THREAD

**Issue by mariusrugan** [arangodb/kube-arangodb#736] opened 2021-06-10 10:16 UTC
Hi, is there a official helm repository for the helm charts or any work in progress?
would be extemly useful for gitops based CI systems.

(otherwise i have to download the chart, repack it & host it somewhere, make sure it's inline with what is officially released, etc. so a lot of overhead)

thanks!

**Comment by david-webill** [comment] 2021-09-30 07:01
Would also appreciate this very much!

**Comment by mysticaltech** [comment] 2021-10-05 09:30
Please close as dupe of https://github.com/arangodb/kube-arangodb/issues/562

**Comment by bo0ts** [comment] 2023-07-06 11:45
@mysticaltech I'm confused. It seems the helm repo is gone again and your documentation changes are gone as well. This is really annoying because not having a helm repository is really inconvenient.

**Comment by mysticaltech** [comment] 2023-07-06 16:29
@bo0ts I'm a user too just like you! If I understood well, they never had a properly working helm repo. Just follow their docs and install helm from their zip links.

**Comment by bo0ts** [comment] 2023-07-06 16:40
@mysticaltech unfortunately I want to package the operator as a helm dependency which does not work easily without a repo.

**Comment by mysticaltech** [comment] 2023-07-06 16:45
I see, you have two solutions IMHO, try both.

GPT4 it can help you run your own repo automatically and probably for free on gh pages.

And ping the team to ask them about a repo, if they have one, and if not, why not. 

Good luck!

**Comment by ajanikow** [comment] 2024-07-24 09:15
Hello!

Information about repo added to readme.

Best,
Adam.

**Closed by ajanikow** 2024-07-24 09:15 UTC

**Comment by mysticaltech** [comment] 2024-07-24 10:38
Wonderful, thanks @ajanikow
