### ISSUE TITLE
Finalizers preventing lost node resilience

### ISSUE THREAD

**Issue by kvahed** [arangodb/kube-arangodb#440] opened 2019-08-22 08:50 UTC
When a node is removed from a cluster, the finalisers for arangodb pods prevent rescheduling of said pods on other available nodes. Furthermore, the status of the affected pod does not get updated any more and it is listed with readiness `1/1` and status `Terminating`.

**Comment by maierlars** [comment] 2019-09-27 12:02
Caused by `pod_termination.go` not able to find the node anymore.

> Furthermore, the status of the affected pod does not get updated any more and it is listed with readiness 1/1 and status Terminating.

This is unrelated to the operator. Updating the pod status is done by kubelet of the node on the pod it was assigned to.

**Comment by maierlars** [comment] 2019-09-30 08:06
Was already fix: https://github.com/arangodb/kube-arangodb/commit/fc8063c9cd9cb19b78a26eeb7db976e4a3a53145

**Closed by maierlars** 2019-09-30 08:06 UTC
Labels: 1 Bug, 3 Kubernetes
